title: "Meadowland"
remote_theme: pmarsceill/just-the-docs
##logo: "/assets/images/logo.png"

collections:
  docs:
    permalink: "/Pages/"
    permalink: "/rp/"
    output: true
    
    
aux_links:
  "Desktop Meadow on Itch.io":
    - "https://samperson.itch.io/meadow"    
    


# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Enable or disable heading anchors
heading_anchors: true

#exclude files from menu bar matching the following
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"
, "docs/tests/",
fonts.md,
letterbg.md,
spritesheets.md
]

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "The meadowland team does not own the Desktop Meadow, we work closely with Samperson to ensure a safe environment where content can be shared <a href=\"https://samperson.itch.io/meadow\">Click here to go to the Desktop Meadow Itch.io page</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
